DROP TABLE IF EXISTS room_data;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
);

CREATE TABLE room (
    room_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(user_id),
    room_name TEXT NOT NULL,
    room_description TEXT,
);

CREATE TABLE room_data (
    room_id INTEGER REFERENCES room(room_id),
    -- date_added TIMESTAMP DEFAULT now() NOT NULL,
    temperature INTEGER,
    rH INTEGER,
    CO2 INTEGER,
    light INTEGER,
    comments TEXT,
);
