DROP TABLE IF EXISTS room_data;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS cultivate_users;

-- CREATE TABLE rooms (user_id TEXT, password TEXT)

CREATE TABLE cultivate_users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL
);

CREATE TABLE rooms (
    room_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES cultivate_users(user_id),
    room_name TEXT NOT NULL,
    room_description TEXT
);

CREATE TABLE room_data (
    room_id INTEGER REFERENCES rooms(room_id),
    date_added TEXT NOT NULL,
    temperature INTEGER,
    rh INTEGER,
    co2 INTEGER,
    light INTEGER,
    comments TEXT
);
